---
title: "AN588-Week-2"
author: "Emily Yang"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Working with Other Data Structures
**Challenge 1**


```{r Challenge 1}
library(dplyr)
library(tidyr)
library(stringr)

# Single vector
v <- ("Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed blah blah")
#Sub strings
x <- str_split(v, " ")
x
# Make the string into 8x3 matrix. 
m <- matrix(data = x[[1]] , nrow = 8, ncol = 3, byrow = TRUE)
m
# Pull out the third column which contains every third word
b <- m[,c(3)]
b
```
**Challenge 2**
```{r Challenge 2}
m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
m
# Select columns 2,3,6. Comma before c
x <- m[,c(2,3,6)]
x
# Select rows 6 to 8. Comma after c
x <- m[c(6:8),]
x
# Select row 2, column 2 to row 6, column 9. (2,2) to (6,9)
x <- m[c(2:6),c(2:9)]
x
```
**Challenge 3**
```{r Challenge 3}
a <- array(data = 400:1, dim = c(5,5,4,4))
#All 4D specified so return 1 value
a[1, 1, 1, 2]
# 3 Dimensions specified and returns all possibilites of the 4th
a[2, 3, 2,]
# 2 dimensions have range so 2D
a[1:5, 1:5, 3, 3]
```
**Challenge 4**
```{r Challenge 4, }
Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae",
    "Daubentoniidae")
Lorisoidea <- c("Lorisidae", "Galagidae")
Strepsirhini <- list(Lemuroidea, Lorisoidea)
names(Strepsirhini) <- list("Lemuroidea", "Lorisoidea")
Strepsirhini
Platyrrhini <- c("Cebidae", "Atelidae", "Pitheciidae")
Catarrhini <- c("Cercopithecidae", "Hylobatidae", "Hominidae")
Anthropoidea <- list(Platyrrhini, Catarrhini)
names(Anthropoidea) <- list("Platyrrhini", "Catarrhini")
Anthropoidea
Tarsioidea <- c("Tarsiidae")
Haplorhini <- list(Anthropoidea, Tarsioidea)
names(Haplorhini) <- list("Anthropoidea", "Tarsioidea")
Haplorhini
Primates <- list(Haplorhini, Strepsirhini)
names(Primates) <- list("Haplorhini", "Strepsirhini") 
Primates
Phylogeny <- list(Primates)
names(Phylogeny) <- list("Primates")
Phylogeny


```
**Challenge 5**
```{r Challenge 5}
m3 <- matrix(data = c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2), nrow = 5, ncol = 3, byrow = TRUE)

df <- m3
df
l <- as.logical(df[,c(2)])
f <- as.factor(df[,c(3)])
str(l)
str(f)
```